language: ruby
sudo: false
rvm:
- ruby-head
- 2.3.0
- 2.2
- 2.1
- 1.9.3
- jruby

# upgrading bundler since our gemspec relying on lib/hermann_jars.rb being
# present causes troubles with bundler .17.x
before_install:
    - gem install bundler -N --version ">= 1.8.0"
#deploy:
#  provider: rubygems
#  gemspec: hermann.gemspec
#  api_key:
#    secure: NQDoSKjV0bs2MSZHHwP6gsG3a8JXCCT5nCHiggTvVV2vvFS9WCyBtMDY3WxQzAU/Zbt+FcPobOvbd53HW5hQYkDOpc84j/utVyBBZCtew0wjEY+Z18ygr+oUQtoALoaRh+cr3MUEFA1Q68fsLlzpRH4M6ZQxbUNOQtwNHgLaZco=
